name: 'Commit Keyword Releaser Action'
description: 'Creates releases based on a keyword in Commit Message'
runs:
   using: 'docker'
   image: 'Dockerfile'
branding:
   icon: 'gift'
   color: 'blue'